# 作業二(Due 2026/03/31):
資工二 113590021 邱冠勛

## Problem 
請用 "date = "2026/03/16" 分析股市的開盤價和收盤價的平均值和標準差。

In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
date = "20260316"
url = f'https://www.twse.com.tw/exchangeReport/MI_INDEX?response=json&date={date}&type=ALLBUT0999'
response = requests.get(url, verify=False)  # 忽略 SSL 證書驗證
response_json = response.json()

# 找到每日收盤行情的數據
stock_data = []
stock_fields = []
for table in response_json['tables']:
    if "每日收盤行情" in table['title']:  # 確保是股票成交資訊
        stock_data = table['data']  # 股票成交數據
        stock_fields = table['fields']  # 欄位名稱
        break

# 確保有數據才建立 DataFrame
if stock_data and stock_fields:
    stock = pd.DataFrame(stock_data, columns=stock_fields)
else:
    print("Error: 未找到每日收盤行情的數據")

stock.head()

/home/yfhd/Documents/114-2/Data Science/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.twse.com.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,元大台灣50,"105,392,137","135,317","7,994,232,270",76.30,76.70,75.45,75.60,<p style= color:green>-</p>,0.35,75.55,"2,075",75.60,69,0.00
1,0051,元大中型100,"151,898","1,061","16,590,643",109.20,110.00,108.25,109.75,<p style= color:red>+</p>,1.15,109.50,2,109.80,1,0.00
2,0052,富邦科技,"40,639,135","24,138","1,837,960,832",45.50,45.72,44.96,45.17,<p style= color:green>-</p>,0.13,45.16,492,45.17,384,0.00
3,0053,元大電子,"18,326",196,"3,091,634",169.60,169.60,167.90,169.05,<p style= color:green>-</p>,0.55,167.90,1,168.75,1,0.00
4,0055,元大MSCI金融,"234,868",566,"7,644,018",32.35,32.69,32.35,32.62,<p style= color:red>+</p>,0.27,32.61,1,32.62,2,0.00

In [ ]:
def convert_to_numeric(price):
    valid=(price!='--')

    num_price = pd.to_numeric(
        pd.Series(price).astype(str).str.replace(',', '', regex=False),
        errors='coerce'
    ).to_numpy()

    return num_price[valid].astype(float)

### 結果顯示

In [43]:
open_dayprice = convert_to_numeric( np.array(stock.開盤價) )
close_dayprice = convert_to_numeric( np.array(stock.收盤價) )

data = {
    '類別': ["開盤", "收盤",],
    '平均值': [open_dayprice.mean(), close_dayprice.mean()],
    '標準差': [ open_dayprice.std(), close_dayprice.std()]
}

pd.DataFrame(data)

   類別         平均值         標準差
0  開盤  109.315630  349.197893
1  收盤  108.497391  344.125381